### ISSUE TITLE
add feature to support to take user defined `container` and `container_version`

### ISSUE THREAD

**Issue by lindaxiang** [icgc-argo-workflows/nextflow-data-processing-utility-tools#41]
Currently it is hard coded to use images from 
- `overture/score`, see [example](https://github.com/icgc-argo-workflows/nextflow-data-processing-utility-tools/blob/main/process/score_download.nf#L37). 
- `overture/song-client`, see [example](https://github.com/icgc-argo-workflows/nextflow-data-processing-utility-tools/blob/main/process/song_get_analysis.nf#L35)

**Comment by lindaxiang** [comment]
This has been addressed by 
- https://github.com/icgc-argo-workflows/nextflow-data-processing-utility-tools/pull/47
- https://github.com/icgc-argo-workflows/nextflow-data-processing-utility-tools/pull/44

**Comment by b-f-chan** [comment]
Closing since already addressed
