### ISSUE TITLE
update to new repo for the song/score packages 

### ISSUE THREAD

**Issue by lindaxiang** [icgc-argo-workflows/nextflow-data-processing-utility-tools#42]
This repo was migrated from [old repo](https://github.com/icgc-argo/nextflow-data-processing-utility-tools), while the repo info has not been updated. 
Need to make them updated so that the release carry the correct repo info.

**Comment by lindaxiang** [comment]
This has been addressed by 
- https://github.com/icgc-argo-workflows/nextflow-data-processing-utility-tools/pull/47
- https://github.com/icgc-argo-workflows/nextflow-data-processing-utility-tools/pull/44

**Comment by b-f-chan** [comment]
Closing since already addressed
